### ISSUE TITLE
1.9.3-3 takes my site down.

### ISSUE THREAD

**Issue by gregbrant2** [oncletom/wp-less#122]
Hi,

First, thanks for your work on WP-Less. 🤟

I'm experiencing issues with WP-Less with my site hosted on wordpress.com. 
It was working fine before the 1.9.3 issue, though I don't know what version we had installed. (The site is run by the marketing department). Since then I can't get any version working. I've tried rolling back to 1.8, 1.7.6 and 1.7.5. 

We're hosted on wordpress.com, so we're using whatever versions of PHP etc they supply.

I've enabled `WP_DEBUG` and I get the following error message with 1.9.3-3 installed.

Any help appreceated! 

```
[22-Sep-2021 14:30:26 UTC] PHP Warning:  filemtime(): stat failed for /srv/htdocs/wp-content/https://mydomain.com/wp-content/themes/pillar/style/css/theme.less in /srv/htdocs/wp-content/plugins/wp-less/lib/Stylesheet.class.php on line 94
[22-Sep-2021 14:30:26 UTC] PHP Fatal error:  Uncaught Exception: load error: failed to find /srv/htdocs/wp-content/https://mydomain.com/wp-content/themes/pillar/style/css/theme.less in /srv/htdocs/wp-content/plugins/wp-less/vendor/wikimedia/less.php/lessc.inc.php:144
Stack trace:
#0 /srv/htdocs/wp-content/plugins/wp-less/vendor/wikimedia/less.php/lessc.inc.php(242): lessc->compileFile('/srv/htdocs/wp-...')
#1 /srv/htdocs/wp-content/plugins/wp-less/lib/Compiler.class.php(75): lessc->cachedCompile('/srv/htdocs/wp-...', true)
#2 /srv/htdocs/wp-content/plugins/wp-less/lib/Plugin.class.php(255): WPLessCompiler->cacheStylesheet(Object(WPLessStylesheet), true)
#3 /srv/htdocs/wp-content/plugins/wp-less/lib/Plugin.class.php(285): WPLessPlugin->processStylesheet('ebor-theme-styl...', true)
#4 /wordpress/core/5.8.1/wp-includes/class-wp-hook.php(301): WPLessPlugin->processStylesheets()
#5 /wordpress/core/5.8.1/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/core/5.8.1/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#7 /wordpress/core/5.8.1/wp-includes/script-loader.php(2083): do_action('wp_enqueue_scri...')
#8 /wordpress/core/5.8.1/wp-includes/class-wp-hook.php(303): wp_enqueue_scripts('')
#9 /wordpress/core/5.8.1/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#10 /wordpress/core/5.8.1/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#11 /wordpress/core/5.8.1/wp-includes/general-template.php(3015): do_action('wp_head')
#12 /srv/htdocs/wp-content/themes/pillar/header.php(8): wp_head()
#13 /wordpress/core/5.8.1/wp-includes/template.php(770): require_once('/srv/htdocs/wp-...')
#14 /wordpress/core/5.8.1/wp-includes/template.php(716): load_template('/srv/htdocs/wp-...', true, Array)
#15 /wordpress/core/5.8.1/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#16 /srv/htdocs/wp-content/themes/pillar/page_visual_composer.php(2): get_header()
#17 /wordpress/core/5.8.1/wp-includes/template-loader.php(106): include('/srv/htdocs/wp-...')
#18 /wordpress/core/5.8.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#19 /wordpress/core/5.8.1/index.php(17): require('/wordpress/core...')
#20 {main}
  thrown in /srv/htdocs/wp-content/plugins/wp-less/vendor/wikimedia/less.php/lessc.inc.php on line 144
```

**Comment by gregbrant2** [comment]
@oncletom did you have chance to look at this? Thanks

**Comment by DavidSteinbauer** [comment]
@gregbrant2 @oncletom struggling with the same issue and found out that it only appears when using with composer or git tracking. when uploading manually via FTP it is working.

**Comment by oncletom** [comment]
Hello,

Sorry for not being available to solve the problem.

Sadly I have no time to allocate on this. If you rely on me to solve the problem, and if that's critical for you, my suggestion would be to contribute to help fix the issue — it applies to anyone who is reading this exchange, not just @DavidSteinbauer and @gregbrant2.

**Comment by pixelbart** [comment]
I would say that this is a case for wikimedia/lessphp and not WP-Less. WP-Less only uses the wikimedia parser and it doesn't seem to work properly with older PHP versions.

So it would make sense to report the error here: https://github.com/wikimedia/less.php/issues

But the basic problem is that lessphp is not really kept up to date. Even with the wikimedia port, not much happens.

I personally have no problems with me. Whether included in the theme, or activated as a plugin. Even with new installations there are no problems. I am talking about PHP 7.4 to 8.1.

**Comment by bmulholland** [comment]
Except I've also tried 1.9.3-3 and it also takes my site down: https://wordpress.org/support/topic/version-1-9-compile-error/

No one's followed up on that in over a month, though...

**Comment by DavidSteinbauer** [comment]
@pixelbart @oncletom okay. I will have a look but also Please keep in mind, that wpackagist has issues with 
the current 1.9.3 **-3** Version. As they only work with "." not with "-"

ref. https://wpackagist.org/search?q=wp-less&type=any&search=
